import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/home/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFonts = localFont({
  src: [
    { path: "../fonts/Barlow-Thin.woff2", weight: "100", style: "normal" },
    {
      path: "../fonts/Barlow-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    { path: "../fonts/Barlow-Light.woff2", weight: "300", style: "normal" },
    { path: "../fonts/Barlow-Regular.woff2", weight: "400", style: "normal" },
    { path: "../fonts/Barlow-Italic.woff2", weight: "400", style: "italic" },
    { path: "../fonts/Barlow-Medium.woff2", weight: "500", style: "normal" },
    { path: "../fonts/Barlow-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../fonts/Barlow-Bold.woff2", weight: "700", style: "normal" },
    { path: "../fonts/Barlow-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../fonts/Barlow-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-barlow",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFonts.className}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
